
package br.usp.ime.choreos.vvws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SimpleStoreWS", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleStoreWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByArtist", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.SearchByArtist")
    @ResponseWrapper(localName = "searchByArtistResponse", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.SearchByArtistResponse")
    public String searchByArtist(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByGenre", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.SearchByGenre")
    @ResponseWrapper(localName = "searchByGenreResponse", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.SearchByGenreResponse")
    public String searchByGenre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByTitle", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.SearchByTitle")
    @ResponseWrapper(localName = "searchByTitleResponse", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.SearchByTitleResponse")
    public String searchByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "purchase", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.Purchase")
    @ResponseWrapper(localName = "purchaseResponse", targetNamespace = "http://ws.vvws.choreos.ime.usp.br/", className = "br.usp.ime.choreos.vvws.ws.PurchaseResponse")
    public Boolean purchase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
