<?xml version="1.0" encoding="UTF-8"?>
<definitions name="GlobalWeatherWSService" targetNamespace="http://choreos.eu/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:tns="http://choreos.eu/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://choreos.eu/" schemaLocation="globalWeather_xsd_1"/>
    </xsd:schema>
  </types>
  <message name="getWeather">
    <part name="parameters" element="tns:getWeather">
    </part>
  </message>
  <message name="getWeatherResponse">
    <part name="parameters" element="tns:getWeatherResponse">
    </part>
  </message>
  <portType name="GlobalWeatherWS">
    <operation name="getWeather">
      <input message="tns:getWeather" wsam:Action="http://choreos.eu/GlobalWeatherWS/getWeatherRequest">
    </input>
      <output message="tns:getWeatherResponse" wsam:Action="http://choreos.eu/GlobalWeatherWS/getWeatherResponse">
    </output>
    </operation>
  </portType>
  <binding name="GlobalWeatherWSPortBinding" type="tns:GlobalWeatherWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getWeather">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="GlobalWeatherWSService">
    <port name="GlobalWeatherWSPort" binding="tns:GlobalWeatherWSPortBinding">
      <soap:address location="http://localhost:9876/globalWeather"/>
    </port>
  </service>
</definitions>
